export const NAVIGATOR_MAPPING = {
  "who-we-are": "Who We Are",
  "life-at-novelex": "Life at Novelex",
  services: "Services",
  careers: "Careers",
  "purpose-value-and-strategy": "Purpose, Value and Strategy",
  "our-people": "Our People",
  "global-impact": "Global Impact",
  "diversity-and-inclusion": "Diversity and Inclusion",
  "climate-strategy": "Climate Strategy",
  "our-partners": "Our Partners",
  "experiencing-novelex": "Experiencing Novelex",
  "events-and-highlights": "Events and Highlights",
  "team-and-culture-insights": "Team and Culture Insights",
  "community-engagement": "Community Engagement",
  "wellness-and-benefits": "Wellness and Benefits",
  "multilingual-solutions": "Multilingual Solutions",
  "language-consultancy": "Language Consultancy",
  interpretation: "Interpretation",
  "mobile-interpretation": "Mobile Interpretation",
  "document-translation": "Document Translation",
  "digital-and-tech-solutions": "Digital and Tech Solutions",
  "training-programme": "Training Programme",
  "join-our-team": "Join Our Team",
  "explore-career-opportunities": "Explore Career Opportunities",
  "become-a-trainer": "Become a Trainer",
  "where-we-hire": "Where We Hire",
  "find-a-job": "Find a Job",
  "professional-development": "Professional Development",
};
