export const NAVIGATOR_MAPPING = {
  "who-we-are": "Who We Are",
  "life-at-novelex": "Life at Novelex",
  services: "Services",
  careers: "Careers",

  "purpose-value-and-strategy": "Purpose, Value and Strategy",
  "our-people": "Our People",
  "global-impact": "Global Impact",
  "diversity-and-inclusion": "Diversity and Inclusion",
  "climate-strategy": "Climate Strategy",
  "our-partners": "Our Partners",

  "experiencing-novelex": "Experiencing Novelex",
  "events-and-highlights": "Events and Highlights",
  "team-and-culture-insights": "Team and Culture Insights",
  "community-engagement": "Community Engagement",
  "wellness-and-benefits": "Wellness and Benefits",

  "multilingual-solutions": "Multilingual Solutions",
  "language-consultancy": "Language Consultancy",
  interpretation: "Interpretation",
  "mobile-interpretation": "Mobile Interpretation",
  "document-translation": "Document Translation",
  "digital-and-tech-solutions": "Digital and Tech Solutions",
  "training-programme": "Training Programme",

  "join-our-team": "Join Our Team",
  "explore-career-opportunities": "Explore Career Opportunities",
  "become-a-trainer": "Become a Trainer",
  "where-we-hire": "Where We Hire",
  "find-a-job": "Find a Job",
  "professional-development": "Professional Development",

  "our-purpose": "Our purpose",
  "our-values": "Our Values",
  "our-strategy": "Our Strategy",
  "meet-our-team": "Meet Our Team",
  "career-growth": "Career Growth",
  "employee-benefits": "Employee Benefits",
  "our-global-reach": "Our Global Reach",
  "social-initiatives": "Social Initiatives",
  "our-commitment": "Our Commitment",
  "inclusivity-initiatives": "Inclusivity Initiatives",
  "diverse-perspectives": "Diverse Perspectives",
  "environmental-stewardship": "Environmental Stewardship",
  "sustainable-practices": "Sustainable Practices",
  "green-initiatives": "Green Initiatives",
  "strategic-alliances": "Strategic Alliances",
  "collaborative-ventures": "Collaborative Ventures",
  "partner-success-stories": "Partner Success Stories",
  "our-culture": "Our Culture",
  "event-calendar": "Event Calendar",
  achievements: "Achievements",
  "spotlight-stories": "Spotlight Stories",
  "teamwork-and-collaboration": "Teamwork and Collaboration",
  "cultural-insights": "Cultural Insights",
  "employee-experiences": "Employee Experiences",
  "social-impact": "Social Impact",
  volunteerism: "Volunteerism",
  "community-partnerships": "Community Partnerships",
  "employee-wellness": "Employee Wellness",
  "benefits-packages": "Benefits Packages",
  "work-life-balance": "Work-Life Balance",
  "comprehensive-services": "Comprehensive Services",
  "real-time-translation": "Real-time Translation",
  "interpretation-services": "Interpretation Services",
  "language-solutions": "Language Solutions",
  "consultation-services": "Consultation Services",
  "language-training": "Language Training",
  "real-time-interpretation": "Real-time Interpretation",
  "on-the-go-translation": "On-the-Go Translation",
  "mobile-app-integration": "Mobile App Integration",
  "instant-language-support": "Instant Language Support",
  "document-translation-services": "Document Translation Services",
  "certified-translation": "Certified Translation",
  "content-localization": "Content Localization",
  "digital-language-tools": "Digital Language Tools",
  "language-software": "Language Software",
  "tech-integration": "Tech Integration",
  "language-training-programs": "Language Training Programs",
  "language-career-pathways": "Language Career Pathways",
};
